# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - 'test'
        - 'prod'
  
env:
  CANCEL: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest  
    steps:    
      # Runs a single command using the runners shell
      - name: Run a one-line script 
        if: ${{ github.event.inputs.name }} == 'test'
        run: echo Test

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        if: ${{ github.event.inputs.name }} == 'prod'
        run: |
          echo Prod 
